<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            //Scented Candle
            [
                'collection_name' => 'Scented Candle',
                'product_type' => 'Signature by Zodiac 130gr',
                'variants' => '12 Zodiac',
                'price_2024' => 199000,
                'price_2025' => 219000,
                'net_price' => 142350,
                'image' => 'images/scented_candle1.jpg',
                'notes' => 'Include pouch',
            ],
            [
                'collection_name' => 'Scented Candle',
                'product_type' => 'Everyday Collection 130gr',
                'variants' => 'Roasted Spice, Creamy Latte, Honey Milk Tea',
                'price_2024' => 199000,
                'price_2025' => 219000,
                'net_price' => 142350,
                'image' => 'images/scented_candle2.jpg',
                'notes' => null,
            ],
            [
                'collection_name' => 'Scented Candle',
                'product_type' => 'Timeless Collection 130gr',
                'variants' => 'Faith, Hope, Love, Peace',
                'price_2024' => 199000,
                'price_2025' => 219000,
                'net_price' => 142350,
                'image' => 'images/scented_candle3.jpg',
                'notes' => null,
            ],
            [
                'collection_name' => 'Scented Candle',
                'product_type' => 'Signature by Zodiac 90gr',
                'variants' => '12 Zodiac',
                'price_2024' => 109000,
                'price_2025' => 139000,
                'net_price' => 90350,
                'image' => 'images/scented_candle4.jpg',
                'notes' => null,
            ],
            [
                'collection_name' => 'Scented Candle',
                'product_type' => 'Everyday Collection 90gr',
                'variants' => 'Roasted Spice, Creamy Latte, Honey Milk Tea',
                'price_2024' => 109000,
                'price_2025' => 139000,
                'net_price' => 90350,
                'image' => 'images/scented_candle2.jpg',
                'notes' => null,
            ],
            [
                'collection_name' => 'Scented Candle',
                'product_type' => 'Wax Sachet',
                'variants' => 'Faith, Love, Hope, Peace',
                'price_2024' => null,
                'price_2025' => 69000,
                'net_price' => 44850,
                'image' => 'images/scented_candle3.jpg',
                'notes' => 'New product',
            ],
            [
                'collection_name' => 'Scented Candle',
                'product_type' => 'Mosquito Repellent 200gr',
                'variants' => 'Citronella, Lemongrass, Orange',
                'price_2024' => null,
                'price_2025' => 229000,
                'net_price' => 148850,
                'image' => 'images/scented_candle4.jpg',
                'notes' => null,
            ],

            //Freshener / Fragrance
            [
                'collection_name' => 'Freshener / Fragrance',
                'product_type' => 'Mini Hanging Diffuser 10ml',
                'variants' => 'Heritage, Fleur Fraiche, Mind Refresher, Good Mood, Just Relax',
                'price_2024' => 69000,
                'price_2025' => 69000,
                'net_price' => 44850,
                'image' => 'images/mini_diffuser.jpg',
                'notes' => 'Blend of natural oil and witch hazel',
            ],
            [
                'collection_name' => 'Freshener / Fragrance',
                'product_type' => 'Reed Diffuser 50ml',
                'variants' => 'Blossom Spring, Renjana, Arunika',
                'price_2024' => 189000,
                'price_2025' => 189000,
                'net_price' => 122850,
                'image' => 'images/reed_diffuser1.jpg',
                'notes' => null,
            ],
            [
                'collection_name' => 'Freshener / Fragrance',
                'product_type' => 'Reed Diffuser 35ml',
                'variants' => 'Blossom Spring, Renjana',
                'price_2024' => 129000,
                'price_2025' => 149000,
                'net_price' => 96850,
                'image' => 'images/reed_diffuser2.jpg',
                'notes' => null,
            ],
            [
                'collection_name' => 'Freshener / Fragrance',
                'product_type' => 'Linen Spray 100ml',
                'variants' => 'Blossom, Energetic, Romance, Warm & Spice',
                'price_2024' => 119000,
                'price_2025' => 119000,
                'net_price' => 77350,
                'image' => 'images/linen_spray.jpg',
                'notes' => 'Blend of natural oil, witch hazel, and 96% ethanol',
            ],
            [
                'collection_name' => 'Freshener / Fragrance',
                'product_type' => 'Artisan EDP Signature Collection 30ml',
                'variants' => 'Lucé, Briélle, Angél, Écho, Xavé, Davé',
                'price_2024' => null,
                'price_2025' => 209000,
                'net_price' => 135850,
                'image' => 'images/signature_perfume.jpg',
                'notes' => null,
            ],
            [
                'collection_name' => 'Freshener / Fragrance',
                'product_type' => 'Artisan EDP Daily Collection 30ml',
                'variants' => 'Iris Musk, Bergamot Vanilla, Citrus White Tea, Lilac Amber, Violet Rose',
                'price_2024' => 159000,
                'price_2025' => 169000,
                'net_price' => 109850,
                'image' => 'images/artisan_perfume.jpg',
                'notes' => null,
            ],

            //Treatment
            [
                'collection_name' => 'Treatment',
                'product_type' => 'Natural Hand Oil 20ml',
                'variants' => 'Bergamot-Lavender, Lemon Myrrh, Myrtle Juniper',
                'price_2024' => 89000,
                'price_2025' => 109000,
                'net_price' => 70850,
                'image' => 'images/hand_oil.jpg',
                'notes' => 'Blend of Essential Oil, Apricot Kernel Oil, Jojoba Oil, and Vitamin E Oil',
            ],
            [
                'collection_name' => 'Treatment',
                'product_type' => 'Massage Oil 120ml',
                'variants' => 'After Work, Peaceful Night, Serenity',
                'price_2024' => 159000,
                'price_2025' => 189000,
                'net_price' => 122850,
                'image' => 'images/massage_oil.jpg',
                'notes' => 'Blend of Essential Oil, Coconut Oil, and Apricot Kernel Oil',
            ],
            [
                'collection_name' => 'Treatment',
                'product_type' => 'Massage Candle 90gr',
                'variants' => 'Lemongrass-Orange, Lavender-Vanilla',
                'price_2024' => null,
                'price_2025' => 239000,
                'net_price' => 239000,
                'image' => 'images/massage_candle.jpg',
                'notes' => 'Blend of Essential Oil, Cera Alba, Shea Butter, and Cocoa Butter',
            ],
            [
                'collection_name' => 'Treatment',
                'product_type' => 'Healing Roll On 10gr',
                'variants' => '7 Variants with Crystal',
                'price_2024' => null,
                'price_2025' => 89000,
                'net_price' => 57850,
                'image' => 'images/healing_rollon.jpg',
                'notes' => 'Blend of Essential Oil, Apricot Kernel Oil, Jojoba Oil, and Vitamin E Oil',
            ],
        ]);
    }
}
